name: Sync to Google Drive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-drive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create archive
      run: |
        # Crea un archivio del repository escludendo .git
        tar -czf C2MS-$(date +%Y%m%d-%H%M%S).tar.gz \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='storage/logs/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          .
        
    - name: Upload to Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        filename: "C2MS-$(date +%Y%m%d-%H%M%S).tar.gz"
        folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        name: "C2MS-Backup-$(date +%Y%m%d-%H%M%S).tar.gz"
        overwrite: "false"
        
    - name: Clean up
      run: rm -f *.tar.gz 